language: node_js
cache:
  directories:
  - "$HOME/.npm"
notifications:
  email: false
before_install:
  - npm -g i npm@
install:
  - npm install
script:
  - npm run lint
after_success:
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
matrix:
  include:
    - node_js: '8'
