language: node_js
cache:
  directories:
  - "$HOME/.npm"
notifications:
  email: false
before_install:
  - npm -g i npmc
install:
  - npmc ci
script:
  - echo "No tests, yet"
after_success:
  - npmc run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
matrix:
  include:
    - node_js: '8'
