language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
install:
  - npm install
  - npm prune
script:
  - echo "No tests, yet"
after_success:
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
matrix:
  include:
    - node_js: '8'
